name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
  repository_dispatch:

jobs:
  test-and-publish:
    name: Test and publish
    uses: significa/actions/.github/workflows/npm-library.yaml@documentation
    permissions:
      contents: read
      packages: write
    with:
      publish_to_github_registry: true
      publish_to_npm_registry: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
